### ISSUE TITLE
web hosting

### ISSUE THREAD

**Issue by cljag** [raphiz/passwordcards#2]
hi, I can't run the code on my own server, may you explain how i can upload and set up it on ftp server please? thanks

**Comment by raphiz** [comment]
Just to let you know, I am no longer actively maintaining this project, so some parts of it (especially the PHP version used and probably all dependencies) are outdated and may not work on modern PHP hosters. I used to deploy this project with a [simple script](https://github.com/raphiz/passwordcards/blob/master/deploy.sh) - maybe that's helpful for you. 

Apart from that, I can't offer more support. Feel free to fork the project and adapt it to your needs if that's an option.

Thanks for your understanding, and good luck with your setup!

**Comment by cljag** [comment]
thanks!
